--------------------------------------------------------
--  File created - Saturday-September-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPLICATIONS
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."APPLICATIONS" 
   (	"APPLICATION_ID" NUMBER, 
	"STUDENT_ID" NUMBER, 
	"JOB_ID" NUMBER, 
	"APPLICATION_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30 BYTE) DEFAULT 'Applied'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPANIES
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."COMPANIES" 
   (	"COMPANY_ID" NUMBER, 
	"COMPANY_NAME" VARCHAR2(100 BYTE), 
	"INDUSTRY" VARCHAR2(100 BYTE), 
	"LOCATION" VARCHAR2(100 BYTE), 
	"HR_EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."COURSE" 
   (	"COURSE_ID" NUMBER, 
	"COURSE_NAME" VARCHAR2(30 BYTE), 
	"CREDITS" NUMBER, 
	"DEPT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."DEPARTMENT" 
   (	"DEPT_ID" NUMBER, 
	"DEPT_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."EMPLOYEE" 
   (	"EMP_ID" NUMBER, 
	"EMP_NAME" VARCHAR2(30 BYTE), 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INTERVIEWS
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."INTERVIEWS" 
   (	"INTERVIEW_ID" NUMBER, 
	"APPLICATION_ID" NUMBER, 
	"INTERVIEW_DATE" DATE, 
	"INTERVIEW_MODE" VARCHAR2(20 BYTE), 
	"RESULT" VARCHAR2(20 BYTE) DEFAULT 'Pending'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOBS
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."JOBS" 
   (	"JOB_ID" NUMBER, 
	"COMPANY_ID" NUMBER, 
	"JOB_TITLE" VARCHAR2(100 BYTE), 
	"JOB_TYPE" VARCHAR2(50 BYTE), 
	"SALARY" NUMBER(10,2), 
	"MINIMUM_CGPA" NUMBER(3,2), 
	"JOB_LOCATION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACEMENTS
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."PLACEMENTS" 
   (	"PLACEMENT_ID" NUMBER, 
	"STUDENT_ID" NUMBER, 
	"COMPANY_ID" NUMBER, 
	"JOB_ID" NUMBER, 
	"PLACEMENT_DATE" DATE DEFAULT SYSDATE, 
	"PACKAGE_LPA" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKILLS
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."SKILLS" 
   (	"SKILL_ID" NUMBER, 
	"SKILL_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."STUDENT" 
   (	"STUDENT_ID" NUMBER, 
	"STUDENT_NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"AGE" NUMBER, 
	"DEPT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."STUDENTS" 
   (	"STUDENT_ID" NUMBER, 
	"STUDENT_NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"CGPA" NUMBER(3,2), 
	"DEPARTMENT_ID" NUMBER, 
	"GRADUATION_YEAR" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT_SKILLS
--------------------------------------------------------

  CREATE TABLE "PLACEMENT_ADMIN"."STUDENT_SKILLS" 
   (	"STUDENT_ID" NUMBER, 
	"SKILL_ID" NUMBER, 
	"SKILL_LEVEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View V_PLACEMENT_REPORT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PLACEMENT_ADMIN"."V_PLACEMENT_REPORT" ("STUDENT_ID", "STUDENT_NAME", "DEPARTMENT_NAME", "COMPANY_NAME", "JOB_TITLE", "PACKAGE_LPA", "PLACEMENT_DATE") AS 
  SELECT s.student_id,
       s.student_name,
       d.department_name,
       c.company_name,
       j.job_title,
       p.package_lpa,
       p.placement_date
FROM placements p
JOIN students s
    ON p.student_id = s.student_id
JOIN departments d
    ON s.department_id = d.department_id
JOIN companies c
    ON p.company_id = c.company_id
JOIN jobs j
    ON p.job_id = j.job_id
;
--------------------------------------------------------
--  DDL for View V_STUDENT_DEPARTMENT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PLACEMENT_ADMIN"."V_STUDENT_DEPARTMENT" ("STUDENT_ID", "STUDENT_NAME", "EMAIL", "CGPA", "DEPARTMENT_NAME") AS 
  SELECT s.student_id,
       s.student_name,
       s.email,
       s.cgpa,
       d.department_name
FROM students s
JOIN departments d
    ON s.department_id = d.department_id
;
REM INSERTING into PLACEMENT_ADMIN.APPLICATIONS
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (401,101,301,to_date('01-08-26','DD-MM-RR'),'Shortlisted');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (402,101,303,to_date('02-08-26','DD-MM-RR'),'Applied');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (403,102,304,to_date('03-08-26','DD-MM-RR'),'Selected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (404,102,306,to_date('04-08-26','DD-MM-RR'),'Shortlisted');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (405,103,305,to_date('05-08-26','DD-MM-RR'),'Rejected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (406,103,307,to_date('06-08-26','DD-MM-RR'),'Applied');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (407,104,304,to_date('07-08-26','DD-MM-RR'),'Selected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (408,104,311,to_date('08-08-26','DD-MM-RR'),'Shortlisted');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (409,105,301,to_date('09-08-26','DD-MM-RR'),'Rejected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (410,105,312,to_date('10-08-26','DD-MM-RR'),'Applied');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (411,106,303,to_date('11-08-26','DD-MM-RR'),'Shortlisted');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (412,106,309,to_date('12-08-26','DD-MM-RR'),'Selected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (413,107,307,to_date('13-08-26','DD-MM-RR'),'Applied');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (414,107,310,to_date('14-08-26','DD-MM-RR'),'Rejected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (415,108,305,to_date('15-08-26','DD-MM-RR'),'Selected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (416,108,311,to_date('16-08-26','DD-MM-RR'),'Shortlisted');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (417,109,306,to_date('17-08-26','DD-MM-RR'),'Selected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (418,110,306,to_date('18-08-26','DD-MM-RR'),'Selected');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (419,111,308,to_date('19-08-26','DD-MM-RR'),'Shortlisted');
Insert into PLACEMENT_ADMIN.APPLICATIONS (APPLICATION_ID,STUDENT_ID,JOB_ID,APPLICATION_DATE,STATUS) values (420,112,311,to_date('20-08-26','DD-MM-RR'),'Applied');
REM INSERTING into PLACEMENT_ADMIN.COMPANIES
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.COMPANIES (COMPANY_ID,COMPANY_NAME,INDUSTRY,LOCATION,HR_EMAIL) values (201,'TCS','Information Technology','Mumbai','hr@tcs.example.com');
Insert into PLACEMENT_ADMIN.COMPANIES (COMPANY_ID,COMPANY_NAME,INDUSTRY,LOCATION,HR_EMAIL) values (202,'Infosys','Information Technology','Bengaluru','hr@infosys.example.com');
Insert into PLACEMENT_ADMIN.COMPANIES (COMPANY_ID,COMPANY_NAME,INDUSTRY,LOCATION,HR_EMAIL) values (203,'Accenture','Technology Consulting','Bengaluru','hr@accenture.example.com');
Insert into PLACEMENT_ADMIN.COMPANIES (COMPANY_ID,COMPANY_NAME,INDUSTRY,LOCATION,HR_EMAIL) values (204,'Cognizant','Information Technology','Chennai','hr@cognizant.example.com');
Insert into PLACEMENT_ADMIN.COMPANIES (COMPANY_ID,COMPANY_NAME,INDUSTRY,LOCATION,HR_EMAIL) values (205,'Deloitte','Consulting and Technology','Hyderabad','hr@deloitte.example.com');
Insert into PLACEMENT_ADMIN.COMPANIES (COMPANY_ID,COMPANY_NAME,INDUSTRY,LOCATION,HR_EMAIL) values (206,'Wipro','Information Technology','Pune','hr@wipro.example.com');
Insert into PLACEMENT_ADMIN.COMPANIES (COMPANY_ID,COMPANY_NAME,INDUSTRY,LOCATION,HR_EMAIL) values (207,'Capgemini','Technology Services','Mumbai','hr@capgemini.example.com');
Insert into PLACEMENT_ADMIN.COMPANIES (COMPANY_ID,COMPANY_NAME,INDUSTRY,LOCATION,HR_EMAIL) values (208,'Tech Mahindra','Information Technology','Pune','hr@techmahindra.example.com');
REM INSERTING into PLACEMENT_ADMIN.COURSE
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.COURSE (COURSE_ID,COURSE_NAME,CREDITS,DEPT_ID) values (501,'DBMS',4,10);
Insert into PLACEMENT_ADMIN.COURSE (COURSE_ID,COURSE_NAME,CREDITS,DEPT_ID) values (502,'Java',3,10);
REM INSERTING into PLACEMENT_ADMIN.DEPARTMENT
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.DEPARTMENT (DEPT_ID,DEPT_NAME) values (10,'Computer Science');
Insert into PLACEMENT_ADMIN.DEPARTMENT (DEPT_ID,DEPT_NAME) values (20,'Commerce');
REM INSERTING into PLACEMENT_ADMIN.DEPARTMENTS
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME) values (1,'MCA');
Insert into PLACEMENT_ADMIN.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME) values (2,'MCA - Generative AI');
REM INSERTING into PLACEMENT_ADMIN.EMPLOYEE
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.EMPLOYEE (EMP_ID,EMP_NAME,DEPARTMENT,SALARY) values (101,'Ravi','IT',40000);
Insert into PLACEMENT_ADMIN.EMPLOYEE (EMP_ID,EMP_NAME,DEPARTMENT,SALARY) values (102,'Arun','HR',35000);
Insert into PLACEMENT_ADMIN.EMPLOYEE (EMP_ID,EMP_NAME,DEPARTMENT,SALARY) values (103,'Kiran','Finance',45000);
REM INSERTING into PLACEMENT_ADMIN.INTERVIEWS
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (501,401,to_date('10-08-26','DD-MM-RR'),'Online','Passed');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (502,403,to_date('12-08-26','DD-MM-RR'),'Online','Passed');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (503,404,to_date('14-08-26','DD-MM-RR'),'Offline','Pending');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (504,407,to_date('15-08-26','DD-MM-RR'),'Online','Passed');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (505,408,to_date('17-08-26','DD-MM-RR'),'Online','Pending');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (506,411,to_date('18-08-26','DD-MM-RR'),'Offline','Passed');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (507,412,to_date('19-08-26','DD-MM-RR'),'Online','Passed');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (508,415,to_date('20-08-26','DD-MM-RR'),'Offline','Passed');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (509,416,to_date('21-08-26','DD-MM-RR'),'Online','Pending');
Insert into PLACEMENT_ADMIN.INTERVIEWS (INTERVIEW_ID,APPLICATION_ID,INTERVIEW_DATE,INTERVIEW_MODE,RESULT) values (510,419,to_date('22-08-26','DD-MM-RR'),'Online','Failed');
REM INSERTING into PLACEMENT_ADMIN.JOBS
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (301,201,'Software Developer','Full-Time',650000,7.5,'Mumbai');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (302,201,'Python Developer','Full-Time',700000,7.5,'Pune');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (303,202,'Data Analyst','Full-Time',750000,7.8,'Bengaluru');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (304,202,'AI/ML Engineer','Full-Time',900000,8,'Bengaluru');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (305,203,'Associate Software Engineer','Full-Time',800000,7.5,'Bengaluru');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (306,203,'Generative AI Engineer','Full-Time',1100000,8,'Hyderabad');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (307,204,'Java Developer','Full-Time',650000,7.5,'Chennai');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (308,204,'Data Engineer','Full-Time',850000,7.8,'Chennai');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (309,205,'Technology Analyst','Full-Time',900000,8,'Hyderabad');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (310,206,'Cloud Engineer','Full-Time',800000,7.5,'Pune');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (311,207,'Machine Learning Engineer','Full-Time',950000,8,'Mumbai');
Insert into PLACEMENT_ADMIN.JOBS (JOB_ID,COMPANY_ID,JOB_TITLE,JOB_TYPE,SALARY,MINIMUM_CGPA,JOB_LOCATION) values (312,208,'Full Stack Developer','Full-Time',700000,7.5,'Pune');
REM INSERTING into PLACEMENT_ADMIN.PLACEMENTS
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.PLACEMENTS (PLACEMENT_ID,STUDENT_ID,COMPANY_ID,JOB_ID,PLACEMENT_DATE,PACKAGE_LPA) values (601,101,201,301,to_date('25-08-26','DD-MM-RR'),6.5);
Insert into PLACEMENT_ADMIN.PLACEMENTS (PLACEMENT_ID,STUDENT_ID,COMPANY_ID,JOB_ID,PLACEMENT_DATE,PACKAGE_LPA) values (602,102,202,304,to_date('26-08-26','DD-MM-RR'),9);
Insert into PLACEMENT_ADMIN.PLACEMENTS (PLACEMENT_ID,STUDENT_ID,COMPANY_ID,JOB_ID,PLACEMENT_DATE,PACKAGE_LPA) values (603,104,202,304,to_date('27-08-26','DD-MM-RR'),9);
Insert into PLACEMENT_ADMIN.PLACEMENTS (PLACEMENT_ID,STUDENT_ID,COMPANY_ID,JOB_ID,PLACEMENT_DATE,PACKAGE_LPA) values (604,106,205,309,to_date('28-08-26','DD-MM-RR'),9);
Insert into PLACEMENT_ADMIN.PLACEMENTS (PLACEMENT_ID,STUDENT_ID,COMPANY_ID,JOB_ID,PLACEMENT_DATE,PACKAGE_LPA) values (605,108,203,305,to_date('29-08-26','DD-MM-RR'),8);
Insert into PLACEMENT_ADMIN.PLACEMENTS (PLACEMENT_ID,STUDENT_ID,COMPANY_ID,JOB_ID,PLACEMENT_DATE,PACKAGE_LPA) values (606,109,203,306,to_date('30-08-26','DD-MM-RR'),11);
Insert into PLACEMENT_ADMIN.PLACEMENTS (PLACEMENT_ID,STUDENT_ID,COMPANY_ID,JOB_ID,PLACEMENT_DATE,PACKAGE_LPA) values (607,110,203,306,to_date('31-08-26','DD-MM-RR'),11);
REM INSERTING into PLACEMENT_ADMIN.SKILLS
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (1,'Python');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (2,'Java');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (3,'SQL');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (4,'Data Structures');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (5,'Machine Learning');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (6,'Deep Learning');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (7,'Generative AI');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (8,'Natural Language Processing');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (9,'Power BI');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (10,'Cloud Computing');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (11,'Docker');
Insert into PLACEMENT_ADMIN.SKILLS (SKILL_ID,SKILL_NAME) values (12,'Git and GitHub');
REM INSERTING into PLACEMENT_ADMIN.STUDENT
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.STUDENT (STUDENT_ID,STUDENT_NAME,EMAIL,AGE,DEPT_ID) values (101,'Monish','monish@gmail.com',22,10);
REM INSERTING into PLACEMENT_ADMIN.STUDENTS
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (101,'Aarav Sharma','aarav.sharma@example.com','9000000001',8.45,1,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (102,'Riya Patel','riya.patel@example.com','9000000002',8.72,1,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (103,'Aditya Mehta','aditya.mehta@example.com','9000000003',7.95,1,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (104,'Neha Shah','neha.shah@example.com','9000000004',9.12,1,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (105,'Rahul Verma','rahul.verma@example.com','9000000005',8.18,1,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (106,'Kavya Iyer','kavya.iyer@example.com','9000000006',8.67,1,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (107,'Arjun Nair','arjun.nair@example.com','9000000007',7.84,1,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (108,'Meera Joshi','meera.joshi@example.com','9000000008',9.25,1,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (109,'Siddharth Rao','siddharth.rao@example.com','9000000009',8.91,2,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (110,'Ananya Desai','ananya.desai@example.com','9000000010',9.38,2,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (111,'Dhruv Kapoor','dhruv.kapoor@example.com','9000000011',8.36,2,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (112,'Ishita Singh','ishita.singh@example.com','9000000012',8.79,2,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (113,'Yash Malhotra','yash.malhotra@example.com','9000000013',7.68,2,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (114,'Tanvi Kulkarni','tanvi.kulkarni@example.com','9000000014',9.05,2,2027);
Insert into PLACEMENT_ADMIN.STUDENTS (STUDENT_ID,STUDENT_NAME,EMAIL,PHONE,CGPA,DEPARTMENT_ID,GRADUATION_YEAR) values (115,'Kunal Gupta','kunal.gupta@example.com','9000000015',8.52,2,2027);
REM INSERTING into PLACEMENT_ADMIN.STUDENT_SKILLS
SET DEFINE OFF;
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (101,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (101,3,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (101,5,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (102,2,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (102,3,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (102,4,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (103,1,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (103,3,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (103,12,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (104,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (104,5,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (104,8,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (105,2,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (105,3,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (105,4,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (106,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (106,5,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (106,9,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (107,2,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (107,3,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (107,10,'Beginner');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (108,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (108,3,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (108,5,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (109,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (109,5,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (109,7,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (109,8,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (110,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (110,6,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (110,7,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (110,8,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (111,3,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (111,5,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (111,10,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (112,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (112,7,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (112,8,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (113,3,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (113,4,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (113,12,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (114,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (114,5,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (114,7,'Intermediate');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (115,1,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (115,3,'Advanced');
Insert into PLACEMENT_ADMIN.STUDENT_SKILLS (STUDENT_ID,SKILL_ID,SKILL_LEVEL) values (115,11,'Intermediate');
--------------------------------------------------------
--  DDL for Index PK_STUDENT_SKILLS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PLACEMENT_ADMIN"."PK_STUDENT_SKILLS" ON "PLACEMENT_ADMIN"."STUDENT_SKILLS" ("STUDENT_ID", "SKILL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APPLICATIONS_STATUS
--------------------------------------------------------

  CREATE INDEX "PLACEMENT_ADMIN"."IDX_APPLICATIONS_STATUS" ON "PLACEMENT_ADMIN"."APPLICATIONS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_STUDENT_JOB
--------------------------------------------------------

  CREATE UNIQUE INDEX "PLACEMENT_ADMIN"."UQ_STUDENT_JOB" ON "PLACEMENT_ADMIN"."APPLICATIONS" ("STUDENT_ID", "JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_STUDENT_PLACEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PLACEMENT_ADMIN"."UQ_STUDENT_PLACEMENT" ON "PLACEMENT_ADMIN"."PLACEMENTS" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_VALIDATE_INTERVIEW
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PLACEMENT_ADMIN"."TRG_VALIDATE_INTERVIEW" 
BEFORE INSERT ON interviews
FOR EACH ROW
DECLARE
    v_status applications.status%TYPE;
BEGIN
    SELECT status
    INTO v_status
    FROM applications
    WHERE application_id = :NEW.application_id;

    IF v_status NOT IN ('Shortlisted', 'Selected') THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Interview requires a Shortlisted or Selected application.'
        );
    END IF;
END;

/
ALTER TRIGGER "PLACEMENT_ADMIN"."TRG_VALIDATE_INTERVIEW" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_VALIDATE_PLACEMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PLACEMENT_ADMIN"."TRG_VALIDATE_PLACEMENT" 
BEFORE INSERT ON placements
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM applications
    WHERE student_id = :NEW.student_id
      AND job_id = :NEW.job_id
      AND status = 'Selected';

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Placement requires a Selected application.'
        );
    END IF;
END;

/
ALTER TRIGGER "PLACEMENT_ADMIN"."TRG_VALIDATE_PLACEMENT" ENABLE;
--------------------------------------------------------
--  DDL for Procedure PROC_STUDENT_APPLICATIONS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PLACEMENT_ADMIN"."PROC_STUDENT_APPLICATIONS" (
    p_student_id IN NUMBER
)
AS
BEGIN
    FOR rec IN (
        SELECT s.student_name,
               c.company_name,
               j.job_title,
               a.status
        FROM applications a
        JOIN students s
            ON a.student_id = s.student_id
        JOIN jobs j
            ON a.job_id = j.job_id
        JOIN companies c
            ON j.company_id = c.company_id
        WHERE s.student_id = p_student_id
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            rec.student_name || ' | ' ||
            rec.company_name || ' | ' ||
            rec.job_title || ' | ' ||
            rec.status
        );
    END LOOP;
END;

/
--------------------------------------------------------
--  DDL for Procedure PROC_TOTAL_APPLICATIONS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PLACEMENT_ADMIN"."PROC_TOTAL_APPLICATIONS" 
AS
    v_total NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_total
    FROM applications;
    DBMS_OUTPUT.PUT_LINE('Total Applications: ' || v_total);
END;

/
--------------------------------------------------------
--  DDL for Function FN_APPLICATION_COUNT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PLACEMENT_ADMIN"."FN_APPLICATION_COUNT" (
    p_student_id IN NUMBER
)
RETURN NUMBER
AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM applications
    WHERE student_id = p_student_id;

    RETURN v_count;
END;

/
--------------------------------------------------------
--  DDL for Function FN_AVG_PACKAGE_BY_DEPT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PLACEMENT_ADMIN"."FN_AVG_PACKAGE_BY_DEPT" (
    p_department_id IN NUMBER
)
RETURN NUMBER
AS
    v_avg_package NUMBER;
BEGIN
    SELECT AVG(p.package_lpa)
    INTO v_avg_package
    FROM placements p
    JOIN students s
        ON p.student_id = s.student_id
    WHERE s.department_id = p_department_id;

    RETURN v_avg_package;
END;

/
--------------------------------------------------------
--  DDL for Function GROSS_SALARY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PLACEMENT_ADMIN"."GROSS_SALARY" (
    basic_salary NUMBER
)
RETURN NUMBER
IS
    hra NUMBER;
    da NUMBER;
BEGIN
    hra := basic_salary * 0.20;
    da := basic_salary * 0.10;

    RETURN basic_salary + hra + da;
END;

/
--------------------------------------------------------
--  DDL for Function SAL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PLACEMENT_ADMIN"."SAL" (BASIC NUMBER)
RETURN NUMBER
IS
BEGIN
RETURN BASIC + (BASIC *20 / 100);
END;

/
--------------------------------------------------------
--  DDL for Function SALARY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PLACEMENT_ADMIN"."SALARY" (basic NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN basic + (basic * 20 / 100);
END;

/
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."DEPARTMENT" MODIFY ("DEPT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."DEPARTMENT" ADD PRIMARY KEY ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."DEPARTMENT" ADD UNIQUE ("DEPT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."COURSE" MODIFY ("COURSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."COURSE" ADD CHECK (credits > 0) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."COURSE" ADD PRIMARY KEY ("COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT_SKILLS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT_SKILLS" ADD CONSTRAINT "CHK_SKILL_LEVEL" CHECK (skill_level IN ('Beginner', 'Intermediate', 'Advanced')) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT_SKILLS" ADD CONSTRAINT "PK_STUDENT_SKILLS" PRIMARY KEY ("STUDENT_ID", "SKILL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."EMPLOYEE" ADD PRIMARY KEY ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."DEPARTMENTS" MODIFY ("DEPARTMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."DEPARTMENTS" ADD PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."DEPARTMENTS" ADD UNIQUE ("DEPARTMENT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT" MODIFY ("STUDENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT" ADD CHECK (age >= 18) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT" ADD PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."JOBS" MODIFY ("COMPANY_ID" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."JOBS" MODIFY ("JOB_TITLE" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."JOBS" ADD CONSTRAINT "CHK_JOB_SALARY" CHECK (salary > 0) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."JOBS" ADD CONSTRAINT "CHK_JOB_CGPA" CHECK (minimum_cgpa BETWEEN 0 AND 10) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."JOBS" ADD PRIMARY KEY ("JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."APPLICATIONS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."APPLICATIONS" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."APPLICATIONS" ADD CONSTRAINT "CHK_APPLICATION_STATUS" CHECK (status IN ('Applied', 'Shortlisted', 'Rejected', 'Selected')) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."APPLICATIONS" ADD PRIMARY KEY ("APPLICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."APPLICATIONS" ADD CONSTRAINT "UQ_STUDENT_JOB" UNIQUE ("STUDENT_ID", "JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INTERVIEWS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."INTERVIEWS" MODIFY ("APPLICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."INTERVIEWS" MODIFY ("INTERVIEW_DATE" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."INTERVIEWS" ADD CONSTRAINT "CHK_INTERVIEW_MODE" CHECK (interview_mode IN ('Online', 'Offline')) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."INTERVIEWS" ADD CONSTRAINT "CHK_INTERVIEW_RESULT" CHECK (result IN ('Pending', 'Passed', 'Failed')) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."INTERVIEWS" ADD PRIMARY KEY ("INTERVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."STUDENTS" MODIFY ("STUDENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENTS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENTS" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENTS" ADD CONSTRAINT "CHK_STUDENT_CGPA" CHECK (cgpa BETWEEN 0 AND 10) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENTS" ADD PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENTS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKILLS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."SKILLS" MODIFY ("SKILL_NAME" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."SKILLS" ADD PRIMARY KEY ("SKILL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."SKILLS" ADD UNIQUE ("SKILL_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLACEMENTS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" MODIFY ("COMPANY_ID" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" ADD CONSTRAINT "CHK_PACKAGE" CHECK (package_lpa > 0) ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" ADD PRIMARY KEY ("PLACEMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" ADD CONSTRAINT "UQ_STUDENT_PLACEMENT" UNIQUE ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPANIES
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."COMPANIES" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "PLACEMENT_ADMIN"."COMPANIES" ADD PRIMARY KEY ("COMPANY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."COMPANIES" ADD UNIQUE ("COMPANY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."COMPANIES" ADD UNIQUE ("HR_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."APPLICATIONS" ADD CONSTRAINT "FK_APPLICATION_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "PLACEMENT_ADMIN"."STUDENTS" ("STUDENT_ID") ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."APPLICATIONS" ADD CONSTRAINT "FK_APPLICATION_JOB" FOREIGN KEY ("JOB_ID")
	  REFERENCES "PLACEMENT_ADMIN"."JOBS" ("JOB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."COURSE" ADD FOREIGN KEY ("DEPT_ID")
	  REFERENCES "PLACEMENT_ADMIN"."DEPARTMENT" ("DEPT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INTERVIEWS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."INTERVIEWS" ADD CONSTRAINT "FK_INTERVIEW_APPLICATION" FOREIGN KEY ("APPLICATION_ID")
	  REFERENCES "PLACEMENT_ADMIN"."APPLICATIONS" ("APPLICATION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."JOBS" ADD CONSTRAINT "FK_JOB_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "PLACEMENT_ADMIN"."COMPANIES" ("COMPANY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLACEMENTS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" ADD CONSTRAINT "FK_PLACEMENT_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "PLACEMENT_ADMIN"."STUDENTS" ("STUDENT_ID") ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" ADD CONSTRAINT "FK_PLACEMENT_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "PLACEMENT_ADMIN"."COMPANIES" ("COMPANY_ID") ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."PLACEMENTS" ADD CONSTRAINT "FK_PLACEMENT_JOB" FOREIGN KEY ("JOB_ID")
	  REFERENCES "PLACEMENT_ADMIN"."JOBS" ("JOB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT" ADD FOREIGN KEY ("DEPT_ID")
	  REFERENCES "PLACEMENT_ADMIN"."DEPARTMENT" ("DEPT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."STUDENTS" ADD CONSTRAINT "FK_STUDENT_DEPARTMENT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "PLACEMENT_ADMIN"."DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT_SKILLS
--------------------------------------------------------

  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT_SKILLS" ADD CONSTRAINT "FK_SS_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "PLACEMENT_ADMIN"."STUDENTS" ("STUDENT_ID") ENABLE;
  ALTER TABLE "PLACEMENT_ADMIN"."STUDENT_SKILLS" ADD CONSTRAINT "FK_SS_SKILL" FOREIGN KEY ("SKILL_ID")
	  REFERENCES "PLACEMENT_ADMIN"."SKILLS" ("SKILL_ID") ENABLE;
